website/models.py
from . import db
from sqlalchemy.sql import func

# creating model to interact with DB
class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.String(150))
    date = db.Column(db.DateTime(timezone=True), default=func.now())

website/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from os import path

#creating db object
db = SQLAlchemy()
DB_NAME = "tasks.db"

def create_app():
    ''' Function responsible for creating the web app and define the env variables '''

    # creating flask app
    app = Flask(__name__)

    # defining environment config | Development
    app.config['SECRET_KEY'] = "hello world"
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'

    # Initiating DB in app
    db.init_app(app)

    from .models import Task

    #creates DB file
    create_database(app)

    #adding blueprint routes
    from .routes import routes
    app.register_blueprint(routes, url_prefix="/")

    return app

def create_database(app):
    ''' Function responsible for creating db file if doesnt exist '''

    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import Task
from . import db

routes = Blueprint('routes', __name__)


@routes.route("/")
def home():
    return render_template("home.html")


@routes.route("/list")
def list():
    list = Task.query.all()
    return render_template("list.html", list=list)


@routes.route("/new-task", methods=['GET', 'POST'])
def new_task():
    if request.method == 'POST':
        task = request.form.get('task')

        if len(task)==0:
            return redirect(url_for('routes.new_task'))
        else:
            new_task_add = Task(task=task)

            db.session.add(new_task_add)
            db.session.commit()
            return redirect(url_for('routes.list'))

    else:
        return render_template("new_task.html")


@routes.route("/edit-task/<id>", methods=["GET", "POST"])
def edit_task(id):
    current_task = Task.query.filter_by(id=id).first()

    if request.method == 'POST':
        new_task = request.form.get('task')
        if len(new_task) == 0:
            return redirect(url_for('routes.edit_task', id=id))
        else:
            current_task.task = new_task
            db.session.commit()
            return redirect(url_for('routes.list'))

    else:
        return render_template("new_task.html", current_task=current_task)


@routes.route("/delete-task/<id>", methods=["GET", "POST"])
def delete_task(id):
    current_task = Task.query.filter_by(id=id).first()
    db.session.delete(current_task)
    db.session.commit()
    return redirect(url_for('routes.list'))

website/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <title>Simple CRUD</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">SIMPLE CRUD APP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('routes.home')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('routes.list')}}">To-do List</a>
                </li>

            </ul>
        </div>
    </div>
</nav>
{% block content %}{% endblock %}

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</body>
</html>

website/templates/home.html
{% extends "base_template.html" %}

{% block content %}
<br>
<div class="container">
    <p>
        This app is a simple CRUD to-do list using flask + SQLALCHEMY
    </p>
</div>
{% endblock %}

website/templates/list.html
{% extends "base_template.html" %}

{% block content %}
<div class="container">
<br>
<h1>To-do</h1>
<br>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Task</th>
            <th scope="col">created at</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for item in list %}
        <tr>
            <th scope="row">{{ item.id }}</th>
            <td>{{ item.task }}</td>
            <td>{{ item.date.day }}/{{ item.date.month }}/{{ item.date.year }}</td>
            <td>

                <a type="button" class="close" href="{{url_for('routes.edit_task',id=item.id)}}">
                    <i class="bi bi-pencil-square"></i>

                </a>
                &nbsp; &nbsp;
                <a type="button" class="close" href="{{url_for('routes.delete_task',id=item.id)}}">
                    <i class="bi bi-trash-fill"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div align="center">
        <a class="btn btn-primary" href="{{url_for('routes.new_task')}}" role="button">Add Item</a>
    </div>
</div>

{% endblock %}

website/templates/new_task.html
{% extends "base_template.html" %}

{% block content %}
<div class="container">
<br>
<h1>New Task</h1>
<br>

    <!-- Content here -->

    <form method="post">

        <br>
        <div class="form-group">
            <label for="task">Task:</label>
            {% if current_task %}
            <input type="text" class="form-control" id="task" name="task"
                   value="{{ current_task.task }}">
            {% else %}
            <input type="text" class="form-control" id="task" name="task"
                   placeholder="example - Take out the trash">
            {% endif %}
        </div>

        <br/>
        <div align="center">
            <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> &nbsp;
                Save
            </button>
        </div>

    </form>
</div>

{% endblock %}